name: Build

on:
  push:
    branches:
  pull_request:
    branches:
      - master

defaults:
  run:
    shell: pwsh

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]
        include:
          - os: windows-latest
            PubProfile: SingleFile-R2R-Win64
            PubSubdir: win
            ArcName: Windows
          - os: ubuntu-latest
            PubProfile: SingleFile-R2R-Linux64
            PubSubdir: linux
            ArcName: Linux
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.100-preview.8.20417.9'
      - name: Build
        run: dotnet publish TaigaUpdateGithubProfile.csproj -p:PublishProfile=${{ matrix.PubProfile }}
      - name: Delete git2 PDB
        if: ${{ startsWith(matrix.PubSubdir, 'win') }}
        run: rm bin/Release/net5.0/publish/${{ matrix.PubSubdir }}/git2*
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: TaigaUpdater-${{ matrix.ArcName }}
          path: bin/Release/net5.0/publish/${{ matrix.PubSubdir }}